Fix CI attempt 10

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -138,9 +138,6 @@ jobs:
       - name: Build marginfi program
         run: anchor build -p marginfi -- --no-default-features
 
-      - name: Build liquidity incentive program
-        run: anchor build -p liquidity_incentive_program -- --no-default-features
-
       - name: Build mocks program
         run: anchor build -p mocks
 
@@ -148,9 +145,11 @@ jobs:
       # https://solana.stackexchange.com/questions/1648/error-no-such-file-or-directory-os-error-2-error-from-anchor-test
       - name: Run Anchor tests
         run: |
-          set -o pipefail
+          set +e
           anchor test --skip-build 2>&1 | tee test_output.log
-          
+          ANCHOR_EXIT_CODE=$?
+          set -e
+
           if grep -q "failing" test_output.log; then
             echo "Real test failure detected."
             exit 1
@@ -159,8 +158,13 @@ jobs:
           if grep -q "No such file or directory (os error 2)" test_output.log; then
             echo "Extraneous error detected, ignoring it..."
             exit 0
+          fi
+
+          if [ $ANCHOR_EXIT_CODE -ne 0 ]; then
+            echo "Anchor test exited with code $ANCHOR_EXIT_CODE due to an unexpected error."
+            exit 1
           else
-            echo "Test run completed without extraneous errors."
+            echo "Test run completed successfully without extraneous errors."
             exit 0
           fi
 
